export default {
  MOVIES: 'MOVIES',
  CURRENT_PAGE: 'CURRENT_PAGE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  REMOVE_MOVIE: 'REMOVE_MOVIE',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  SHOW_ROAST_NOTIFY: 'SHOW_ROAST_NOTIFY',
};
